# Generated by Django 4.2.9 on 2024-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='approve',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
